config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/projects', to:"pages#projects"
  get '/contact', to:"pages#contact"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  </head>

  <body class="body">

    <nav class="navbar navbar-expand navbar-personalizado">
      <div class="container-fluid">
        <%= image_tag 'Logo-Fondo-Blanco', class: 'logo_img', width: '50px' %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item mr-5 ml-3" >
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to 'Proyectos', projects_path, class: 'nav-link' %>
          </li>
          <li class="nav-item mr-2">
            <%= link_to 'Contacto', contact_path, class: 'nav-link' %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container">
    <h1>Contacto</h1>
    <form id="contact-form">
      <div class="form-group">
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="name" class="form-control" required>
      </div>
      <div class="form-group">
        <label for="email">Correo electrónico:</label>
        <input type="email" id="email" name="email" class="form-control" required>
      </div>
      <div class="form-group">
        <label for="message">Mensaje:</label>
        <textarea id="message" name="message" class="form-control" rows="5" required></textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Enviar</button>
      </div>
    </form>
  </div>

app/views/pages/home.html.erb
<section>
    <h1 class="mb-4">¡Es mi página principal, poco creativa!</h1>
    <h1 class="mb-4">Sección 1</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer interdum odio in felis mattis feugiat.
      In rhoncus libero magna, ultricies condimentum tortor tempor sit amet. Donec eget ante eu justo malesuada
      fermentum sed ut nunc. Suspendisse vestibulum metus eu consectetur tempus. Mauris id tortor a ante rhoncus
      cursus vel ac leo. Morbi scelerisque massa a elit pulvinar, non tristique ipsum semper. Integer sed nisi
      tincidunt, volutpat nulla vitae, tincidunt ipsum. Mauris consectetur, nunc vel fermentum consequat, felis
      libero euismod est, et tempus tellus tellus eu ex.
    </p>
  </section>

  <section>
    <h1 class="mb-4">Sección 2</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer interdum odio in felis mattis feugiat.
      In rhoncus libero magna, ultricies condimentum tortor tempor sit amet. Donec eget ante eu justo malesuada
      fermentum sed ut nunc. Suspendisse vestibulum metus eu consectetur tempus. Mauris id tortor a ante rhoncus
      cursus vel ac leo. Morbi scelerisque massa a elit pulvinar, non tristique ipsum semper. Integer sed nisi
      tincidunt, volutpat nulla vitae, tincidunt ipsum. Mauris consectetur, nunc vel fermentum consequat, felis
      libero euismod est, et tempus tellus tellus eu ex
    </p>
  </section>

app/views/pages/projects.html.erb
  <div class="container">
    <h1 class="proyecto">Esta es la página de proyectos</h1>
    <div class="row g-3">
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card">
                <%= image_tag 'foto1', class: 'foto1' %>
                <div class="card-body">
                    <h5 class="card-title">Cóctel Sol y Mar</h5>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer interdum odio in felis mattis feugiat. In rhoncus libero magna, ultricies condimentum tortor tempor sit amet.</p>
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn btn-primary" type="button">Ver mas</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card">
                <%= image_tag 'foto2', class: 'foto2' %>
                <div class="card-body">
                    <h5 class="card-title">El Ritmo del Océano</h5>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer interdum odio in felis mattis feugiat. In rhoncus libero magna, ultricies condimentum tortor tempor sit amet.</p>
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn btn-primary" type="button">Ver mas</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card">
                <%= image_tag 'foto3', class: 'foto3' %>
                <div class="card-body">
                    <h5 class="card-title">Sendero hacia el Paraíso</h5>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer interdum odio in felis mattis feugiat. In rhoncus libero magna, ultricies condimentum tortor tempor sit amet.</p>
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn btn-primary" type="button">Ver mas</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>